server:
  port: 8082

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5434/booking_db
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true